# Generated by Django 5.1.6 on 2025-02-26 01:20

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='destino',
            name='preco',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('100'), default_currency='BRL', max_digits=20, validators=[djmoney.models.validators.MinMoneyValidator(100, message='Valor inválido. O valor mínimo é de 100,00 BRL'), djmoney.models.validators.MaxMoneyValidator(30000, message='Valor inválido. O valor Máximo é de 30.000,00 BRL')]),
        ),
    ]
